services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: netassets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./netassets
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: netassets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      DEBUG: "True"
    volumes:
      - ./netassets/assets:/app/assets
      - ./netassets/templates:/app/templates
      - ./netassets/static:/app/static
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 