# Generated by Django 5.2.3 on 2025-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='historicalcomputer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Компьютер', 'verbose_name_plural': 'historical Компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='historicalnetworkdevice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Сетевое устройство', 'verbose_name_plural': 'historical Сетевые устройства'},
        ),
        migrations.AlterModelOptions(
            name='historicalprinter',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Принтер', 'verbose_name_plural': 'historical Принтеры'},
        ),
        migrations.AlterModelOptions(
            name='historicalrouter',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Роутер', 'verbose_name_plural': 'historical Роутеры'},
        ),
        migrations.AlterModelOptions(
            name='historicalswitch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Коммутатор', 'verbose_name_plural': 'historical Коммутаторы'},
        ),
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'verbose_name': 'Сетевое устройство', 'verbose_name_plural': 'Сетевые устройства'},
        ),
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Принтер', 'verbose_name_plural': 'Принтеры'},
        ),
        migrations.AlterModelOptions(
            name='router',
            options={'verbose_name': 'Роутер', 'verbose_name_plural': 'Роутеры'},
        ),
        migrations.AlterModelOptions(
            name='switch',
            options={'verbose_name': 'Коммутатор', 'verbose_name_plural': 'Коммутаторы'},
        ),
        migrations.AlterField(
            model_name='computer',
            name='barcode',
            field=models.CharField(max_length=128, unique=True, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='department',
            field=models.CharField(max_length=128, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения работ'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='inventory_number',
            field=models.CharField(max_length=64, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='network_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='Сетевой адрес'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='pc_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Имя ПК'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='pc_type',
            field=models.CharField(max_length=64, verbose_name='Тип ПК'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='responsible',
            field=models.CharField(max_length=128, verbose_name='Материально ответственный'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='room',
            field=models.CharField(max_length=32, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='seal',
            field=models.CharField(blank=True, max_length=64, verbose_name='Пломба'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(max_length=64, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('on_site', 'На месте'), ('repair', 'В ремонте'), ('setup', 'На настройке'), ('repaired', 'Отремонтирован'), ('decommissioned', 'Списан'), ('configured', 'Настроен'), ('lost', 'Утерян')], max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='barcode',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='department',
            field=models.CharField(max_length=128, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения работ'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='id',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='inventory_number',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='network_address',
            field=models.GenericIPAddressField(db_index=True, verbose_name='Сетевой адрес'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='pc_name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Имя ПК'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='pc_type',
            field=models.CharField(max_length=64, verbose_name='Тип ПК'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='responsible',
            field=models.CharField(max_length=128, verbose_name='Материально ответственный'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='room',
            field=models.CharField(max_length=32, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='seal',
            field=models.CharField(blank=True, max_length=64, verbose_name='Пломба'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='status',
            field=models.CharField(choices=[('on_site', 'На месте'), ('repair', 'В ремонте'), ('setup', 'На настройке'), ('repaired', 'Отремонтирован'), ('decommissioned', 'Списан'), ('configured', 'Настроен'), ('lost', 'Утерян')], max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='code',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='department',
            field=models.CharField(max_length=128, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='device_type',
            field=models.CharField(choices=[('printer', 'Принтер'), ('computer', 'Компьютер'), ('router', 'Роутер'), ('switch', 'Коммутатор'), ('camera', 'Камера'), ('panel', 'Панель'), ('server', 'Сервер')], max_length=16, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='hostname',
            field=models.CharField(max_length=128, verbose_name='Имя хоста'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='location',
            field=models.CharField(max_length=128, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='network_type',
            field=models.CharField(choices=[('Static', 'Статический'), ('DHCP', 'DHCP')], max_length=10, verbose_name='Тип сети'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='subnet',
            field=models.CharField(max_length=64, verbose_name='Подсеть'),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='admin_login',
            field=models.CharField(max_length=64, verbose_name='Логин администратора'),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='admin_password',
            field=models.CharField(max_length=64, verbose_name='Пароль администратора'),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='computers',
            field=models.CharField(max_length=256, verbose_name='Компьютеры для подключения'),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='department',
            field=models.CharField(max_length=128, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='employee_name',
            field=models.CharField(max_length=128, verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='id',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='model',
            field=models.CharField(max_length=128, verbose_name='Модель принтера'),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='printer_name',
            field=models.CharField(max_length=128, verbose_name='Имя принтера'),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='room',
            field=models.CharField(max_length=32, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='admin_login',
            field=models.CharField(max_length=64, verbose_name='Логин администратора'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='admin_password',
            field=models.CharField(max_length=64, verbose_name='Пароль администратора'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='device_type',
            field=models.CharField(max_length=64, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='id',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='model',
            field=models.CharField(max_length=128, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='remote_access',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3, verbose_name='Удалённый доступ'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='room',
            field=models.CharField(max_length=32, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('unavailable', 'Недоступен')], max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='subnet',
            field=models.CharField(max_length=64, verbose_name='Подсеть'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='wifi_password',
            field=models.CharField(max_length=128, verbose_name='Пароль Wi-Fi'),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='wifi_ssid',
            field=models.CharField(max_length=128, verbose_name='Wi-Fi SSID'),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='department',
            field=models.CharField(max_length=128, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='hostname',
            field=models.CharField(max_length=128, verbose_name='Имя хоста'),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='id',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='ip_range',
            field=models.CharField(max_length=64, verbose_name='IP-диапазон'),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='model',
            field=models.CharField(max_length=128, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='node_location',
            field=models.CharField(max_length=128, verbose_name='Расположение узла'),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='port',
            field=models.CharField(max_length=32, verbose_name='Порт'),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='room',
            field=models.CharField(max_length=32, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='status',
            field=models.CharField(choices=[('used', 'Используется'), ('free', 'Свободна')], max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='subnet_mask',
            field=models.CharField(max_length=64, verbose_name='Маска подсети'),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='vlan',
            field=models.CharField(max_length=32, verbose_name='VLAN'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='department',
            field=models.CharField(max_length=128, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(choices=[('printer', 'Принтер'), ('computer', 'Компьютер'), ('router', 'Роутер'), ('switch', 'Коммутатор'), ('camera', 'Камера'), ('panel', 'Панель'), ('server', 'Сервер')], max_length=16, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='hostname',
            field=models.CharField(max_length=128, verbose_name='Имя хоста'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='location',
            field=models.CharField(max_length=128, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='network_type',
            field=models.CharField(choices=[('Static', 'Статический'), ('DHCP', 'DHCP')], max_length=10, verbose_name='Тип сети'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='subnet',
            field=models.CharField(max_length=64, verbose_name='Подсеть'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='admin_login',
            field=models.CharField(max_length=64, verbose_name='Логин администратора'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='admin_password',
            field=models.CharField(max_length=64, verbose_name='Пароль администратора'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='computers',
            field=models.CharField(max_length=256, verbose_name='Компьютеры для подключения'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='department',
            field=models.CharField(max_length=128, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='employee_name',
            field=models.CharField(max_length=128, verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='model',
            field=models.CharField(max_length=128, verbose_name='Модель принтера'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='printer_name',
            field=models.CharField(max_length=128, verbose_name='Имя принтера'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='room',
            field=models.CharField(max_length=32, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='router',
            name='admin_login',
            field=models.CharField(max_length=64, verbose_name='Логин администратора'),
        ),
        migrations.AlterField(
            model_name='router',
            name='admin_password',
            field=models.CharField(max_length=64, verbose_name='Пароль администратора'),
        ),
        migrations.AlterField(
            model_name='router',
            name='device_type',
            field=models.CharField(max_length=64, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='router',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='router',
            name='model',
            field=models.CharField(max_length=128, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='router',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='router',
            name='remote_access',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3, verbose_name='Удалённый доступ'),
        ),
        migrations.AlterField(
            model_name='router',
            name='room',
            field=models.CharField(max_length=32, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='router',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('unavailable', 'Недоступен')], max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='router',
            name='subnet',
            field=models.CharField(max_length=64, verbose_name='Подсеть'),
        ),
        migrations.AlterField(
            model_name='router',
            name='wifi_password',
            field=models.CharField(max_length=128, verbose_name='Пароль Wi-Fi'),
        ),
        migrations.AlterField(
            model_name='router',
            name='wifi_ssid',
            field=models.CharField(max_length=128, verbose_name='Wi-Fi SSID'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='department',
            field=models.CharField(max_length=128, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='hostname',
            field=models.CharField(max_length=128, verbose_name='Имя хоста'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ip_range',
            field=models.CharField(max_length=64, verbose_name='IP-диапазон'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='model',
            field=models.CharField(max_length=128, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='node_location',
            field=models.CharField(max_length=128, verbose_name='Расположение узла'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='port',
            field=models.CharField(max_length=32, verbose_name='Порт'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='room',
            field=models.CharField(max_length=32, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='status',
            field=models.CharField(choices=[('used', 'Используется'), ('free', 'Свободна')], max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='subnet_mask',
            field=models.CharField(max_length=64, verbose_name='Маска подсети'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='vlan',
            field=models.CharField(max_length=32, verbose_name='VLAN'),
        ),
    ]
